name: oag-environment
channels:
  - conda-forge
dependencies:
  - r-essentials
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - r-tidyverse
  - r-lme4
  - r-ggplot2
  - r-gsubfn
  - r-zoo
  - r-data.table
  - r-pander
  - r-scales
  - r-rcurl
  - r-stringr
